// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAkTe3AMDAUBtXXUF8_oG8hotixRiQc-c',
    appId: '1:452277114566:web:76f06c69b74383bf33e9c7',
    messagingSenderId: '452277114566',
    projectId: 'smart-irrigation-76f4e',
    databaseURL:
        "https://smart-irrigation-76f4e-default-rtdb.europe-west1.firebasedatabase.app",
    authDomain: 'smart-irrigation-76f4e.firebaseapp.com',
    storageBucket: 'smart-irrigation-76f4e.appspot.com',
    measurementId: 'G-FTWH36XNM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2fUq6UfvhcbL-WHS_lyoN_uUybIq-imA',
    appId: '1:452277114566:android:fe4413d217ce98e333e9c7',
    messagingSenderId: '452277114566',
    projectId: 'smart-irrigation-76f4e',
    storageBucket: 'smart-irrigation-76f4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAufV81Xq5zgbghA1l-iO_1Z6lj3qobO6g',
    appId: '1:452277114566:ios:31a2bc2ec4fc024033e9c7',
    messagingSenderId: '452277114566',
    projectId: 'smart-irrigation-76f4e',
    storageBucket: 'smart-irrigation-76f4e.appspot.com',
    iosClientId:
        '452277114566-dgdtlcdr80nk799fjrbi0cluo71o20vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAufV81Xq5zgbghA1l-iO_1Z6lj3qobO6g',
    appId: '1:452277114566:ios:26b56b3c423b913e33e9c7',
    messagingSenderId: '452277114566',
    projectId: 'smart-irrigation-76f4e',
    storageBucket: 'smart-irrigation-76f4e.appspot.com',
    iosClientId:
        '452277114566-j6d217bs75t3u9cc6dnnd8de3cjvsbt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTes.RunnerTests',
  );
}
